### ISSUE TITLE
Still getting startup errors.

### ISSUE THREAD

**Issue by Codewow** [Remyk1/Survival-Games#1]
Plugin is still hitting the NoSuchMethod error and can't run any command while producing the in-game error: "Can't connect to server, plugin disabled." error.

Not sure if the two issues are mutually exclusive or not. 

`[11:38:16] [Server thread/WARN]: [SurvivalGames] Task #45 for SurvivalGames v0.6.7 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.<init>(I)V
	at com.thundergemios10.survivalgames.util.ItemReader.read(ItemReader.java:91) ~[?:?]
	at com.thundergemios10.survivalgames.util.Kit.load(Kit.java:32) ~[?:?]
	at com.thundergemios10.survivalgames.util.Kit.<init>(Kit.java:24) ~[?:?]
	at com.thundergemios10.survivalgames.GameManager.LoadKits(GameManager.java:62) ~[?:?]
	at com.thundergemios10.survivalgames.GameManager.setup(GameManager.java:44) ~[?:?]
	at com.thundergemios10.survivalgames.SurvivalGames$Startup.run(SurvivalGames.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-5629554-4c8327f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]`

**Comment by Remyk1** [comment]
> [11:38:16] [Server thread/WARN]: [SurvivalGames] Task #⁠45 for SurvivalGames v0.6.7

It looks like you are  running an older version.

Try the newest version from [releases](https://github.com/Remyk1/Survival-Games/releases).

**Comment by Codewow** [comment]
Alright so the updated plugin starts properly, minus the "Material cannot be null!" error.

`[12:12:52] [Server thread/WARN]: java.lang.IllegalArgumentException: Material cannot be null
[12:12:52] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[12:12:52] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:71)
[12:12:52] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:59)
[12:12:52] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:47)
[12:12:52] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:37)
[12:12:52] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.util.ItemReader.read(ItemReader.java:99)
[12:12:52] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.util.Kit.load(Kit.java:32)
[12:12:52] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.util.Kit.<init>(Kit.java:24)
[12:12:52] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.GameManager.LoadKits(GameManager.java:69)
[12:12:52] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.GameManager.setup(GameManager.java:51)
[12:12:52] [Server thread/WARN]: 	at com.thundergemios10.survivalgames.SurvivalGames$Startup.run(SurvivalGames.java:99)
[12:12:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[12:12:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[12:12:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[12:12:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[12:12:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[12:12:52] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[12:12:52] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[12:12:52] [Server thread/INFO]: null
[12:12:52] [Server thread/INFO]: fire:2
[12:12:52] [Server thread/INFO]: sharpness:4`


But also the plugin doesn't allow adding of arena walls. it will always spew: "[SG][Error] {input} not specified!"

Which does not throw an error in the console, even with debug mode on.

**Comment by Remyk1** [comment]
1. Did you convert the item id's to material names(267 to iron_sword )?
2. Hmm not sure about this one, it seemed to work for me.  
EDIT make sure to use the right syntax /sg addwall arenaId

**Comment by Codewow** [comment]
Got it. It's been a while since we ever had to do something to the plugin. Looks like it's all working so far. I'll have my server test it out and bring any issues over. Thanks for the help.
